# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ExtendedRunMC <- function(grid_, isovalue_, size_x_, size_y_, size_z_, s_x, s_y, s_z) {
    .Call(`_tcie_ExtendedRunMC`, grid_, isovalue_, size_x_, size_y_, size_z_, s_x, s_y, s_z)
}

AnalizeGrid <- function(grid, size_x_, size_y_, size_z_, iso) {
    .Call(`_tcie_AnalizeGrid`, grid, size_x_, size_y_, size_z_, iso)
}

